### ISSUE TITLE
Missing triangles

### ISSUE THREAD

**Issue by m0ppers** [Marzac/le3d#44] opened 2018-07-05 10:29 UTC
I am a bit lost. For one of my models I am getting strange effects. Triangles seem to go missing :(

I tried to create a minimal example but unfortunately I failed. I can really only reproduce it with my skytree.obj.

I have attached some screenshots and the source. When I move upwards a bit I am seeing missing triangles...When I move a bit more to the top the triangles appear. Some calculation seems to fail. I am getting consistent behaviour on all systems (Amiga, Mac and PC).

![grafik](https://user-images.githubusercontent.com/819421/42318082-4931f450-804e-11e8-8eec-db8c1caa05c0.png)
![grafik](https://user-images.githubusercontent.com/819421/42318105-5d1cfbea-804e-11e8-85d1-6cb4ac09ffb8.png)

[planetest.tar.gz](https://github.com/Marzac/le3d/files/2166145/planetest.tar.gz)

**Comment by Marzac** [comment] 2018-07-05 10:50
I have never seen that so far.
I have at least three projects (destroyer, tomato, treasure islands ...) that work with #le3d and do not exhibit such artifacts. I gonna give it a try with your sources tonight.

**Comment by Marzac** [comment] 2018-07-05 11:05
I see now.
Your tower model has triangles inside. Like a second inner cylinder within the outer one.
You can do this respecting some rules as the engine has no z-buffer. A particular attention has to be drawn to the geometry topology.
The distance used for calculating the drawing order is based on each triangle center point distance to camera after potential frustrum clipping. Triangles that overlap should be of about the same size and aspect ratio for proper depth calculation.
However there might be still a bug, I have a look at this.

**Comment by Marzac** [comment] 2018-07-05 11:16
Maybe it's the way that vd (view distance) is calculated that is wrong.

https://github.com/Marzac/le3d/blob/194e6b3f3217e2a5d09161e65ae586bfd196b2f7/engine/renderer.cpp#L499

https://github.com/Marzac/le3d/blob/194e6b3f3217e2a5d09161e65ae586bfd196b2f7/engine/renderer.cpp#L562

https://github.com/Marzac/le3d/blob/194e6b3f3217e2a5d09161e65ae586bfd196b2f7/engine/renderer.cpp#L591

https://github.com/Marzac/le3d/blob/194e6b3f3217e2a5d09161e65ae586bfd196b2f7/engine/renderer.cpp#L739

try with: vd = tri->vd = v->z * v->z - vOffset;

That might solve your problem. Not sure if this is right for all 3D scenes.

**Comment by m0ppers** [comment] 2018-07-05 14:42
ah yeah now I get what is different here...the outer hull is supposed to have some alpha on the texture so the inner part is visible.

Will try with your hack!

**Comment by Marzac** [comment] 2018-07-17 09:13
Any news here?

**Comment by m0ppers** [comment] 2018-07-17 16:03
the hack didn't work. was thinking about creating two different meshes. but didn't find time so far :) would label it "known bug" so far :)

**Comment by Marzac** [comment] 2018-08-13 08:10
The bug lies in the 3d clipping routine.
https://github.com/Marzac/le3d/blob/194e6b3f3217e2a5d09161e65ae586bfd196b2f7/engine/renderer.cpp#L671
There should be a >= instead of a > operator in line 671.
This is corrected in version 1.8.

**Comment by Marzac** [comment] 2018-08-13 22:33
Please tell me if that fixes your problem and I will close this issue.

**Comment by Marzac** [comment] 2018-12-24 12:17
Unable to reproduce here.

**Closed by Marzac** 2018-12-24 12:17 UTC
Labels: bug
